{% set name = "nomad-parser-plugins-simulation" %}
{% set version = "1.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/nomad_parser_plugins_simulation-{{ version }}.tar.gz
  sha256: 8ab115e5e82dfd33a04b44b4080c9634551513e6e95b437667adf8d3d1d4ea71

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - nomad-lab >=1.3.6
    - nomad-schema-plugin-run >=1.0.1

test:
  imports:
    - simulationparsers
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/nomad-coe/nomad-simulations
  summary: Collection of NOMAD parsers for simulation codes.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
